# Generated by Django 3.1.4 on 2020-12-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('userID', models.IntegerField()),
                ('inmoney', models.IntegerField()),
                ('things', models.CharField(choices=[('e', '教育'), ('l', '生活'), ('m', '医疗'), ('f', '理财'), ('s', '工资')], max_length=1, verbose_name='keeping inthings')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='mylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=25)),
                ('operator', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('userID', models.IntegerField()),
                ('outmoney', models.IntegerField()),
                ('things', models.CharField(choices=[('e', '教育'), ('l', '生活'), ('m', '医疗'), ('f', '理财'), ('s', '工资')], max_length=1, verbose_name='keeping outthings')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('passwd', models.CharField(max_length=25)),
            ],
        ),
    ]
