# Generated by Django 3.1.4 on 2020-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeping', '0004_confirmstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
