# Generated by Django 3.1.4 on 2020-12-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeping', '0005_user_has_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='detail',
            field=models.CharField(max_length=255, verbose_name='详细事件'),
        ),
        migrations.AlterField(
            model_name='income',
            name='inmoney',
            field=models.IntegerField(verbose_name='收入金额'),
        ),
        migrations.AlterField(
            model_name='income',
            name='things',
            field=models.CharField(choices=[('e', '教育'), ('l', '生活'), ('m', '医疗'), ('s', '工资')], max_length=1, verbose_name='收入种类'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='detail',
            field=models.CharField(max_length=255, verbose_name='详细事件'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outmoney',
            field=models.IntegerField(verbose_name='支出金额'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='things',
            field=models.CharField(choices=[('e', '教育'), ('l', '生活'), ('m', '医疗'), ('s', '工资')], max_length=1, verbose_name='支出种类'),
        ),
    ]
